import Head from 'next/head';
import styles from '../../styles/Bookmark.module.css';
import Link from 'next/link';
import Image from 'next/image';

import {
  BookmarkBtn,
  BookmarkCard,
  BookmarkFooter,
  FAQ,
  Logo,
} from '../../components';
import {
  Hamburger,
  DesktopImg,
  chromeIcon,
  DesktopImgTwo,
  LogoIcon,
} from '../../public/bookmark';

const Bookmark = () => {
  return (
    <div className={styles.main}>
      <Head>
        <title>Bookmark</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        {/* Navbar */}
        <nav className={styles.navbar}>
          <div className={styles.logo}>{/* <Logo /> */}</div>
          <div className={styles.navItems}></div>
        </nav>
      </main>
    </div>
  );
};
export default Bookmark;
