import Head from 'next/head';
import styles from '../../styles/Bookmark.module.css';
import Link from 'next/link';
import Image from 'next/image';

import { Logo } from '../../components';
import { Hamburger, DesktopImg } from '../../public/assets/bookmark';
import StyledButton from '../../components/styledComponents/Bookmark-btn';

const Bookmark = () => {
  return (
    <div className={styles.main}>
      <Head>
        <title>Bookmark</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        {/* Navbar */}
        <div>
          <nav className={styles.nav}>
            <Logo />

            <div>
              <Image
                className={styles.icon}
                src={Hamburger}
                alt='hamburger Icon'
              />
            </div>
          </nav>
        </div>
        <section className={styles.heroSection}>
          <div className={styles.imgBox}>
            <Image
              src={DesktopImg}
              alt='a desktop image'
              className={styles.heroImage}
              // width={450}
              // height={350}
            />
          </div>

          <div>
            <h1 className={styles.head}>A simple Bookmark Manager</h1>
            <p className={styles.heroInfo}>
              A clean and simple interface to organize your favourite websites.
              Open a new browser tab and see your sites load instantly. Try it
              free.
            </p>
            <StyledButton primary>Get it on Chrome</StyledButton>
            <StyledButton>Get it on Firefox</StyledButton>
          </div>

          {/* Features */}
          <div className={styles.features}>
            <h3 className={styles.featuresHead}>Features</h3>
            <p className={styles.featuresDetails}>
              Our aim is to make it quick and easy for you to access your
              favourite website. Your bookmarks sync between your devices so you
              can access them on the go.
            </p>
            <h3 className={styles.featureOne}>Simple Bookmarking</h3>
            <h3 className={styles.featureTwo}>Speedy Searching</h3>
            <h3 className={styles.featureThree}>Easy Sharing</h3>
          </div>
        </section>
      </main>
    </div>
  );
};
export default Bookmark;
