import Head from 'next/head';
import Link from 'next/link';
import Button from '../components/button/button';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Front-end Mentors Challenges</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.name}>Ehiz</h1>
        <h3 className={styles.greeting}>Hello</h3>
        <p className={styles.info}>
          Lorem ipsum dolor sit, amet consectetur adipisicing elit. Officiis
          quidem omnis ipsum minima dolore? Ratione eaque, quo aliquid eveniet
          illum distinctio, saepe ducimus modi quod dolorem dolores, repellendus
          unde temporibus illo ut! Rem, aperiam consectetur!
        </p>
        <Button>
          <Link href='/projects'>
            <a>Go to Projects</a>
          </Link>
        </Button>
      </main>
    </div>
  );
}

